// Reference stations donated by the sibling BIOL 40B sites.
//
// Images and hand-verified pin positions come from the labeling app
// (~/bio40b-lab-exam-2-labeling, PRESET_KEYS), copied in rather than linked —
// same arrangement the spelling drill uses. These fill the parts of the exam
// the lab-bench photos cannot show: the histology slides, the conduction
// system, and the pericardial layers.
//
// Only the IMAGES are used. DONOR_PINS below is the labeling app's verified
// key, kept for reference but deliberately NOT loaded — every slide on this
// site starts blank, because placing and naming a structure is the studying.
//
// GENERATED by tools/import-donor.py — do not hand-edit.

const DONOR_SLIDES = [
  {
    "id": "ref_heart_internal",
    "src": "images/ref_heart_internal.jpg",
    "title": "Heart — Chambers & Internal Anatomy",
    "hint": "Heart — frontal (coronal) section, anterior view",
    "donor": true
  },
  {
    "id": "ref_heart_surface_ant",
    "src": "images/ref_heart_surface_ant.jpg",
    "title": "Heart — Surface & Great Vessels (anterior)",
    "hint": "Heart — external surface, anterior view",
    "donor": true
  },
  {
    "id": "ref_heart_surface_post",
    "src": "images/ref_heart_surface_post.jpg",
    "title": "Heart — Surface & Great Vessels (posterior)",
    "hint": "Heart — external surface, posterior view",
    "donor": true
  },
  {
    "id": "ref_heart_valves",
    "src": "images/ref_heart_valves.jpg",
    "title": "Heart Valves",
    "hint": "Heart valves — superior view (atria removed)",
    "donor": true
  },
  {
    "id": "ref_heart_conduction",
    "src": "images/ref_heart_conduction.jpg",
    "title": "Cardiac Conduction System",
    "hint": "Cardiac conduction system — anterior view of frontal section",
    "donor": true
  },
  {
    "id": "ref_blood_formed",
    "src": "images/ref_blood_formed.jpg",
    "title": "Blood — Formed Elements",
    "hint": "Blood smear — formed elements (slide #16)",
    "donor": true
  },
  {
    "id": "ref_vessel_cutaway",
    "src": "images/ref_vessel_cutaway.jpg",
    "title": "Blood Vessel — Wall Layers",
    "hint": "Artery wall — layers (slide #3, Artery/Vein/Nerve)",
    "donor": true
  },
  {
    "id": "ref_vessel_cross",
    "src": "images/ref_vessel_cross.jpg",
    "title": "Blood Vessel — Cross-Section",
    "hint": "Artery — cross-section (slide #3)",
    "donor": true
  },
  {
    "id": "ref_cardiac_dia",
    "src": "images/ref_cardiac_dia.jpg",
    "title": "Cardiac Muscle — Intercalated Discs",
    "hint": "Cardiac muscle — intercalated discs (slide #45)",
    "donor": true
  },
  {
    "id": "ref_cardiac_histo",
    "src": "images/ref_cardiac_histo.jpg",
    "title": "Cardiac Muscle — Histology (Slide 45)",
    "hint": "Cardiac muscle — histology (slide #45)",
    "donor": true
  },
  {
    "id": "ref_heart_wall",
    "src": "images/ref_heart_wall.jpg",
    "title": "Heart Wall & Pericardium",
    "hint": "Heart wall & pericardium — layered detail",
    "donor": true
  },
  {
    "id": "ref_resp_overview",
    "src": "images/ref_resp_overview.jpg",
    "title": "Respiratory System Overview",
    "hint": "Respiratory system — overview",
    "donor": true
  },
  {
    "id": "ref_resp_upper",
    "src": "images/ref_resp_upper.jpg",
    "title": "Upper Airway — Nasal Cavity & Pharynx",
    "hint": "Upper airway — nasal cavity & pharynx (sagittal section)",
    "donor": true
  },
  {
    "id": "ref_resp_larynx",
    "src": "images/ref_resp_larynx.jpg",
    "title": "Larynx",
    "hint": "Larynx — anterior view",
    "donor": true
  },
  {
    "id": "ref_resp_lungs",
    "src": "images/ref_resp_lungs.jpg",
    "title": "Lungs — Lobes & Bronchial Tree",
    "hint": "Lungs — lobes & bronchial tree",
    "donor": true
  },
  {
    "id": "ref_resp_alveoli",
    "src": "images/ref_resp_alveoli.jpg",
    "title": "Alveoli — Lung Histology",
    "hint": "Alveoli — lung histology",
    "donor": true
  },
  {
    "id": "ref_resp_trachea_histo",
    "src": "images/ref_resp_trachea_histo.jpg",
    "title": "Trachea — Histology",
    "hint": "Trachea wall — histology (slide #9)",
    "donor": true
  },
  {
    "id": "ref_resp_pleura",
    "src": "images/ref_resp_pleura.jpg",
    "title": "Pleural Membranes",
    "hint": "Pleural membranes (detail)",
    "donor": true
  },
  {
    "id": "ref_resp_muscles",
    "src": "images/ref_resp_muscles.jpg",
    "title": "Respiratory Muscles",
    "hint": "Respiratory muscles — thoracic cavity",
    "donor": true
  }
];

const DONOR_PINS = {
  "ref_heart_internal": [
    {
      "id": "rhear122",
      "x": 0.8092,
      "y": 0.181,
      "label": "Left atrium",
      "lx": 0.85314,
      "ly": 0.22404,
      "func": "Receives oxygenated blood from the pulmonary veins and pumps it to the left ventricle."
    },
    {
      "id": "rhear123",
      "x": 0.7794,
      "y": 0.2622,
      "label": "Left pulmonary veins",
      "lx": 0.84374,
      "ly": 0.31916,
      "func": "Return oxygenated blood from the left lung to the left atrium."
    },
    {
      "id": "rhear124",
      "x": 0.8131,
      "y": 0.3735,
      "label": "Bicuspid (mitral) valve",
      "lx": 0.8131,
      "ly": 0.4235,
      "func": "Left AV valve; prevents backflow from the left ventricle into the left atrium."
    },
    {
      "id": "rhear126",
      "x": 0.8178,
      "y": 0.9454,
      "label": "Endocardium",
      "lx": 0.70403,
      "ly": 1.0,
      "func": "Smooth inner endothelial lining of the heart chambers and valves."
    },
    {
      "id": "rhear129",
      "x": 0.81,
      "y": 0.861,
      "label": "Myocardium",
      "lx": 0.85316,
      "ly": 0.8548,
      "func": "Thick middle layer of cardiac muscle responsible for the heart's contraction."
    },
    {
      "id": "rhear136",
      "x": 0.81,
      "y": 0.8036,
      "label": "Epicardium",
      "lx": 0.861,
      "ly": 0.78504,
      "func": "Outermost layer of the heart wall (the visceral pericardium)."
    },
    {
      "id": "rhear137",
      "x": 0.8042,
      "y": 0.6689,
      "label": "Papillary muscle",
      "lx": 0.85372,
      "ly": 0.70555,
      "func": "Contracts to tension the chordae tendineae, keeping the AV valves closed during ventricular systole."
    },
    {
      "id": "rhear138",
      "x": 0.799,
      "y": 0.5935,
      "label": "Left ventricle",
      "lx": 0.86491,
      "ly": 0.59067,
      "func": "Pumps oxygenated blood into the aorta for systemic circulation; thickest-walled chamber."
    },
    {
      "id": "rhear142",
      "x": 0.1932,
      "y": 0.698,
      "label": "Chordae tendineae",
      "lx": 0.12729,
      "ly": 0.71203,
      "func": "Fibrous cords that anchor the AV-valve cusps to the papillary muscles, preventing valve prolapse."
    },
    {
      "id": "rhear143",
      "x": 0.1932,
      "y": 0.2248,
      "label": "Pulmonary trunk",
      "lx": 0.13357,
      "ly": 0.2467,
      "func": "Carries deoxygenated blood from the right ventricle toward the lungs; splits into the L and R pulmonary arteries."
    },
    {
      "id": "rhear146",
      "x": 0.1909,
      "y": 0.4271,
      "label": "Right atrium",
      "lx": 0.1399,
      "ly": 0.43776,
      "func": "Receives deoxygenated blood from the venae cavae and coronary sinus, then pumps it to the right ventricle."
    },
    {
      "id": "rhear147",
      "x": 0.1964,
      "y": 0.1585,
      "label": "Right pulmonary artery",
      "lx": 0.14069,
      "ly": 0.14443,
      "func": "Carries deoxygenated blood from the pulmonary trunk to the right lung."
    },
    {
      "id": "rhear149",
      "x": 0.1885,
      "y": 0.6193,
      "label": "Right ventricle",
      "lx": 0.14377,
      "ly": 0.61872,
      "func": "Pumps deoxygenated blood into the pulmonary trunk to the lungs."
    },
    {
      "id": "rhear150",
      "x": 0.1901,
      "y": 0.3102,
      "label": "Right pulmonary veins",
      "lx": 0.15401,
      "ly": 0.3366,
      "func": "Return oxygenated blood from the right lung to the left atrium."
    },
    {
      "id": "rhear151",
      "x": 0.2034,
      "y": 0.0686,
      "label": "Superior vena cava",
      "lx": 0.22459,
      "ly": 0.04105,
      "func": "Returns deoxygenated blood from the head, neck, and upper limbs to the right atrium."
    },
    {
      "id": "rhear153",
      "x": 0.2058,
      "y": 0.771,
      "label": "Trabeculae carneae",
      "lx": 0.15715,
      "ly": 0.78503,
      "func": "Muscular ridges on the internal walls of the ventricles."
    },
    {
      "id": "rhear155",
      "x": 0.1846,
      "y": 0.5485,
      "label": "Tricuspid valve",
      "lx": 0.14458,
      "ly": 0.55129,
      "func": "Right AV valve; prevents backflow from the right ventricle into the right atrium during ventricular contraction."
    },
    {
      "id": "rhear156",
      "x": 0.6193,
      "y": 0.7564,
      "label": "Interventricular septum",
      "lx": 0.68678,
      "ly": 0.75582,
      "func": "Muscular wall that separates the right and left ventricles."
    },
    {
      "id": "rhear157",
      "x": 0.1917,
      "y": 0.9172,
      "label": "Inferior vena cava",
      "lx": 0.1917,
      "ly": 0.9672,
      "func": "Returns deoxygenated blood from the trunk and lower limbs to the right atrium."
    },
    {
      "id": "rhear158",
      "x": 0.4875,
      "y": 0.0659,
      "label": "Aorta (ascending)",
      "lx": 0.5898,
      "ly": 0.0463,
      "func": "Receives oxygenated blood from the left ventricle and carries it to the systemic circulation."
    },
    {
      "id": "rhear159",
      "x": 0.6785,
      "y": 0.1465,
      "label": "Left pulmonary artery",
      "lx": 0.75267,
      "ly": 0.07439,
      "func": "Carries deoxygenated blood from the pulmonary trunk to the left lung."
    }
  ],
  "ref_heart_surface_ant": [
    {
      "id": "rhear160",
      "x": 0.7547,
      "y": 0.8863,
      "label": "Anterior interventricular artery",
      "lx": 0.883,
      "ly": 0.8659,
      "func": "Runs in the anterior interventricular groove supplying both ventricles and the septum (the 'LAD')."
    },
    {
      "id": "rhear161",
      "x": 0.6557,
      "y": 0.1679,
      "label": "Aortic arch",
      "lx": 0.89532,
      "ly": 0.15833,
      "func": "Curve of the aorta that gives off the brachiocephalic, left common carotid, and left subclavian arteries."
    },
    {
      "id": "rhear164",
      "x": 0.6274,
      "y": 0.9946,
      "label": "Apex of heart",
      "lx": 0.79438,
      "ly": 0.98357,
      "func": "Inferior pointed tip of the heart, formed by the left ventricle."
    },
    {
      "id": "rhear165",
      "x": 0.7151,
      "y": 0.7993,
      "label": "Great cardiac vein",
      "lx": 0.86227,
      "ly": 0.78473,
      "func": "Collects deoxygenated blood from the anterior heart and empties into the coronary sinus."
    },
    {
      "id": "rhear166",
      "x": 0.2802,
      "y": 0.3106,
      "label": "Ascending aorta",
      "lx": 0.20473,
      "ly": 0.30999,
      "func": "Carries oxygenated blood from the left ventricle to the body; gives rise to the coronary arteries."
    },
    {
      "id": "rhear167",
      "x": 0.7019,
      "y": 0.6073,
      "label": "Left coronary artery",
      "lx": 0.84152,
      "ly": 0.60145,
      "func": "Supplies oxygenated blood to the left side of the heart; branches into the circumflex and anterior interventricular arteries."
    },
    {
      "id": "rhear170",
      "x": 0.6906,
      "y": 0.2024,
      "label": "Ligamentum arteriosum",
      "lx": 0.82645,
      "ly": 0.22273,
      "func": "Fetal remnant of the ductus arteriosus, connecting the pulmonary trunk to the aortic arch."
    },
    {
      "id": "rhear171",
      "x": 0.7434,
      "y": 0.4363,
      "label": "Auricle of left atrium",
      "lx": 0.87548,
      "ly": 0.42173,
      "func": "Ear-like flap that increases the volume capacity of the left atrium."
    },
    {
      "id": "rhear172",
      "x": 0.2632,
      "y": 0.6195,
      "label": "Right coronary artery",
      "lx": 0.13962,
      "ly": 0.60493,
      "func": "Supplies oxygenated blood to the right side of the heart."
    },
    {
      "id": "rhear173",
      "x": 0.2509,
      "y": 0.5113,
      "label": "Right auricle",
      "lx": 0.11599,
      "ly": 0.43565,
      "func": "Ear-like extension that increases the capacity of the right atrium."
    }
  ],
  "ref_heart_surface_post": [
    {
      "id": "rhear175",
      "x": 0.7179,
      "y": 0.5311,
      "label": "Coronary sinus",
      "lx": 0.84432,
      "ly": 0.53266,
      "func": "Large vein on the posterior heart that drains cardiac (deoxygenated) blood into the right atrium."
    },
    {
      "id": "rhear177",
      "x": 0.7434,
      "y": 0.7474,
      "label": "Posterior interventricular artery",
      "lx": 0.84246,
      "ly": 0.74723,
      "func": "Branch of the right coronary artery supplying the posterior walls of the ventricles."
    },
    {
      "id": "rhear178",
      "x": 0.6943,
      "y": 0.8183,
      "label": "Middle cardiac vein",
      "lx": 0.86505,
      "ly": 0.8337,
      "func": "Drains the posterior heart and empties into the coronary sinus."
    }
  ],
  "ref_heart_valves": [
    {
      "id": "rhear35",
      "x": 0.2368,
      "y": 0.1905,
      "label": "Tricuspid valve",
      "lx": 0.2368,
      "ly": 0.2405,
      "func": "Right AV valve; three cusps; prevents backflow from the right ventricle into the right atrium."
    },
    {
      "id": "rhear36",
      "x": 0.6579,
      "y": 0.1587,
      "label": "Bicuspid (mitral) valve",
      "lx": 0.6579,
      "ly": 0.2087,
      "func": "Left AV valve; two cusps; prevents backflow from the left ventricle into the left atrium."
    },
    {
      "id": "rhear37",
      "x": 0.4342,
      "y": 0.5873,
      "label": "Aortic semilunar valve",
      "lx": 0.4342,
      "ly": 0.6373,
      "func": "Three half-moon cusps; prevents backflow from the aorta into the left ventricle."
    },
    {
      "id": "rhear38",
      "x": 0.4605,
      "y": 0.9206,
      "label": "Pulmonary semilunar valve",
      "lx": 0.4605,
      "ly": 0.9706,
      "func": "Three cusps; prevents backflow from the pulmonary trunk into the right ventricle."
    }
  ],
  "ref_heart_conduction": [
    {
      "id": "rhear180",
      "x": 0.3849,
      "y": 0.4088,
      "label": "Sinoatrial (SA) node",
      "lx": 0.1566,
      "ly": 0.40705,
      "func": "The heart's pacemaker; initiates each heartbeat and sets the heart rate (in the right atrial wall)."
    },
    {
      "id": "rhear181",
      "x": 0.4142,
      "y": 0.5356,
      "label": "Atrioventricular (AV) node",
      "lx": 0.11326,
      "ly": 0.52997,
      "func": "Delays the impulse before it reaches the ventricles, letting the atria finish contracting first."
    },
    {
      "id": "rhear182",
      "x": 0.7925,
      "y": 0.8473,
      "label": "Purkinje fibers",
      "lx": 0.88684,
      "ly": 0.86237,
      "func": "Distribute the impulse through the ventricular myocardium, triggering ventricular contraction."
    },
    {
      "id": "rhear183",
      "x": 0.7925,
      "y": 0.7865,
      "label": "Right and left bundle branches",
      "lx": 0.91231,
      "ly": 0.74336,
      "func": "Conduct the impulse down either side of the interventricular septum toward the apex."
    },
    {
      "id": "rhear184",
      "x": 0.7754,
      "y": 0.5809,
      "label": "Atrioventricular bundle (bundle of His)",
      "lx": 0.8686,
      "ly": 0.52999,
      "func": "Carries the impulse from the AV node into the interventricular septum; the only electrical link between atria and ventricles."
    }
  ],
  "ref_blood_formed": [
    {
      "id": "rbloo44",
      "x": 0.28,
      "y": 0.22,
      "label": "Erythrocytes",
      "lx": 0.28,
      "ly": 0.27,
      "func": "Carry oxygen (and some carbon dioxide) throughout the body using hemoglobin."
    },
    {
      "id": "rbloo46",
      "x": 0.15,
      "y": 0.6,
      "label": "Monocyte",
      "lx": 0.15,
      "ly": 0.65,
      "func": "Largest WBC; leaves the blood to become a macrophage that phagocytizes pathogens and debris."
    },
    {
      "id": "rbloo47",
      "x": 0.4,
      "y": 0.62,
      "label": "Lymphocyte",
      "lx": 0.4,
      "ly": 0.67,
      "func": "WBC of specific immunity — B cells make antibodies, T cells attack infected cells."
    },
    {
      "id": "rbloo48",
      "x": 0.68,
      "y": 0.55,
      "label": "Eosinophil",
      "lx": 0.68,
      "ly": 0.6,
      "func": "Granular WBC that fights parasitic worms and moderates allergic and inflammatory responses."
    },
    {
      "id": "rbloo49",
      "x": 0.87,
      "y": 0.55,
      "label": "Basophil",
      "lx": 0.87,
      "ly": 0.6,
      "func": "Granular WBC that releases histamine (inflammation) and heparin (anticoagulant) during allergic responses."
    },
    {
      "id": "rbloo50",
      "x": 0.77,
      "y": 0.78,
      "label": "Neutrophil",
      "lx": 0.77,
      "ly": 0.83,
      "func": "Most abundant WBC; a first-responder that phagocytizes bacteria."
    },
    {
      "id": "rbloo185",
      "x": 0.6651,
      "y": 0.2478,
      "label": "Platelets",
      "lx": 0.6651,
      "ly": 0.2978,
      "func": "Cell fragments that clot blood and stop bleeding (hemostasis)."
    }
  ],
  "ref_vessel_cutaway": [
    {
      "id": "rvess186",
      "x": 0.667,
      "y": 0.012,
      "label": "Tunica media",
      "lx": 0.66417,
      "ly": 0.03948,
      "func": "Middle layer of smooth muscle and elastic tissue that controls vessel diameter (constriction/dilation)."
    },
    {
      "id": "rvess187",
      "x": 0.5151,
      "y": 0.0375,
      "label": "Tunica externa",
      "lx": 0.51982,
      "ly": 0.02894,
      "func": "Outermost vessel layer of connective tissue that anchors and protects the vessel."
    },
    {
      "id": "rvess189",
      "x": 0.7953,
      "y": 0.3183,
      "label": "Endothelium",
      "lx": 0.88021,
      "ly": 0.31875,
      "func": "Simple squamous epithelium lining the lumen; gives a smooth, low-friction surface for blood flow."
    },
    {
      "id": "rvess190",
      "x": 0.7604,
      "y": 0.6441,
      "label": "Internal elastic lamina",
      "lx": 0.89248,
      "ly": 0.63404,
      "func": "Sheet of elastic tissue between the tunica interna and tunica media."
    }
  ],
  "ref_vessel_cross": [
    {
      "id": "rvess191",
      "x": 0.6623,
      "y": 0.6317,
      "label": "Lumen",
      "lx": 0.82834,
      "ly": 0.60557,
      "func": "The hollow central channel of the vessel through which blood flows."
    },
    {
      "id": "rvess195",
      "x": 0.6085,
      "y": 0.8477,
      "label": "Tunica interna (intima)",
      "lx": 0.78208,
      "ly": 0.95531,
      "func": "Innermost layer lining the lumen; made of endothelium on a thin connective-tissue layer."
    }
  ],
  "ref_cardiac_dia": [
    {
      "id": "rcard196",
      "x": 0.3198,
      "y": 0.4204,
      "label": "Myofiber",
      "lx": 0.3198,
      "ly": 0.4704,
      "func": "A cardiac muscle cell — branched and striated, joined to neighbors by intercalated discs."
    },
    {
      "id": "rcard197",
      "x": 0.3736,
      "y": 0.1037,
      "label": "Intercalated disc",
      "lx": 0.3736,
      "ly": 0.1537,
      "func": "Junction between cardiac muscle cells; its gap junctions let the cells contract in unison."
    }
  ],
  "ref_cardiac_histo": [
    {
      "id": "rcard198",
      "x": 0.5783,
      "y": 0.4525,
      "label": "Nucleus (central)",
      "lx": 0.69811,
      "ly": 0.35335,
      "func": "Cardiac muscle cells are usually uninucleate, with a single centrally placed nucleus."
    },
    {
      "id": "rcard199",
      "x": 0.5,
      "y": 0.4475,
      "label": "Striations",
      "lx": 0.41226,
      "ly": 0.4975,
      "func": "Regular banding of overlapping actin and myosin filaments — cardiac muscle is striated."
    },
    {
      "id": "rcard200",
      "x": 0.9123,
      "y": 0.4746,
      "label": "Myofiber",
      "lx": 0.9123,
      "ly": 0.5246,
      "func": "A cardiac muscle cell — short, branched, and striated, joined end-to-end by intercalated discs."
    }
  ],
  "ref_heart_wall": [
    {
      "id": "rhear202",
      "x": 0.134,
      "y": 0.1903,
      "label": "Endocardium",
      "lx": 0.06513,
      "ly": 0.11386,
      "func": "Smooth inner endothelial lining of the heart chambers and valves."
    },
    {
      "id": "rhear203",
      "x": 0.1377,
      "y": 0.3308,
      "label": "Myocardium",
      "lx": 0.0877,
      "ly": 0.45487,
      "func": "Thick middle layer of cardiac muscle that contracts to pump blood."
    },
    {
      "id": "rhear204",
      "x": 0.6868,
      "y": 0.0715,
      "label": "Pericardial cavity",
      "lx": 0.92454,
      "ly": 0.13172,
      "func": "Fluid-filled space between the visceral and parietal serous layers that lets the heart beat with little friction."
    },
    {
      "id": "rhear205",
      "x": 0.8377,
      "y": 0.272,
      "label": "Fibrous pericardium",
      "lx": 0.91412,
      "ly": 0.27347,
      "func": "Tough outer connective-tissue sac that anchors the heart and keeps it from overfilling."
    },
    {
      "id": "rhear206",
      "x": 0.6434,
      "y": 0.788,
      "label": "Epicardium (visceral serous pericardium)",
      "lx": 0.9217,
      "ly": 0.7767,
      "func": "Outermost layer of the heart wall — the visceral layer of the serous pericardium."
    },
    {
      "id": "rhear209",
      "x": 0.7705,
      "y": 0.5121,
      "label": "Parietal layer of serous pericardium",
      "lx": 0.93612,
      "ly": 0.49697,
      "func": "Serous membrane lining the fibrous pericardium; forms the outer wall of the pericardial cavity."
    }
  ],
  "ref_resp_overview": [
    {
      "id": "rresp210",
      "x": 0.65,
      "y": 0.8851,
      "label": "Diaphragm",
      "lx": 0.17547,
      "ly": 0.87164,
      "func": "Main muscle of inspiration; contracts and flattens to draw air into the lungs."
    },
    {
      "id": "rresp211",
      "x": 0.5245,
      "y": 0.7451,
      "label": "Lung",
      "lx": 0.13393,
      "ly": 0.72289,
      "func": "Organ of gas exchange where oxygen enters the blood and carbon dioxide leaves it."
    },
    {
      "id": "rresp212",
      "x": 0.6028,
      "y": 0.3698,
      "label": "Larynx",
      "lx": 0.22072,
      "ly": 0.36947,
      "func": "Voice box; routes air into the trachea, produces sound, and keeps food out of the airway."
    },
    {
      "id": "rresp213",
      "x": 0.5991,
      "y": 0.2571,
      "label": "Pharynx",
      "lx": 0.79533,
      "ly": 0.23598,
      "func": "Shared passageway that conducts air (and, in its lower parts, food) toward the larynx and esophagus."
    },
    {
      "id": "rresp214",
      "x": 0.6302,
      "y": 0.43,
      "label": "Trachea",
      "lx": 0.79812,
      "ly": 0.43186,
      "func": "Windpipe; conducts air between the larynx and the bronchi."
    },
    {
      "id": "rresp225",
      "x": 0.2387,
      "y": 0.0875,
      "label": "Nasal cavity",
      "lx": 0.2387,
      "ly": 0.1375,
      "func": "Warms, humidifies, and filters incoming air before it travels to the lungs."
    },
    {
      "id": "rresp226",
      "x": 0.6481,
      "y": 0.5996,
      "label": "Main (primary) bronchus",
      "lx": 0.92735,
      "ly": 0.60255,
      "func": "Conducts air from the trachea into a lung."
    }
  ],
  "ref_resp_upper": [
    {
      "id": "rresp227",
      "x": 0.4165,
      "y": 0.8795,
      "label": "Epiglottis",
      "lx": 0.2165,
      "ly": 0.87771,
      "func": "Flap of cartilage that covers the laryngeal opening during swallowing to keep food out of the airway."
    },
    {
      "id": "rresp228",
      "x": 0.4967,
      "y": 0.3855,
      "label": "Uvula",
      "lx": 0.22028,
      "ly": 0.41757,
      "func": "Fleshy tip of the soft palate that helps close off the nasopharynx during swallowing."
    },
    {
      "id": "rresp229",
      "x": 0.7646,
      "y": 0.3406,
      "label": "Hard palate",
      "lx": 0.8863,
      "ly": 0.33184,
      "func": "Bony front of the roof of the mouth that separates the oral and nasal cavities."
    },
    {
      "id": "rresp230",
      "x": 0.4637,
      "y": 0.9631,
      "label": "Trachea",
      "lx": 0.8637,
      "ly": 0.96629,
      "func": "Windpipe; conducts air between the larynx and the bronchi."
    },
    {
      "id": "rresp231",
      "x": 0.7759,
      "y": 0.4004,
      "label": "Soft palate",
      "lx": 0.90326,
      "ly": 0.41454,
      "func": "Muscular back of the palate; rises to block the nasopharynx during swallowing."
    },
    {
      "id": "rresp232",
      "x": 0.2703,
      "y": 0.5797,
      "label": "Oropharynx",
      "lx": 0.20709,
      "ly": 0.58488,
      "func": "Middle part of the pharynx behind the mouth; a shared passage for air and food."
    },
    {
      "id": "rresp233",
      "x": 0.5976,
      "y": 0.6962,
      "label": "Cricoid cartilage",
      "lx": 0.81364,
      "ly": 0.6964,
      "func": "Ring-shaped cartilage that supports the larynx and connects it to the trachea."
    },
    {
      "id": "rresp234",
      "x": 0.4807,
      "y": 0.6215,
      "label": "Laryngopharynx",
      "lx": 0.21561,
      "ly": 0.64959,
      "func": "Lowest part of the pharynx; a shared passage opening into the larynx and esophagus."
    },
    {
      "id": "rresp235",
      "x": 0.4948,
      "y": 0.3118,
      "label": "Nasopharynx",
      "lx": 0.20046,
      "ly": 0.36578,
      "func": "Uppermost part of the pharynx behind the nasal cavity; an air-only passage."
    },
    {
      "id": "rresp236",
      "x": 0.5401,
      "y": 0.6962,
      "label": "Vocal fold (vocal cords)",
      "lx": 0.16746,
      "ly": 0.71931,
      "func": "Folds in the larynx that vibrate as air passes to produce sound."
    },
    {
      "id": "rresp237",
      "x": 0.4802,
      "y": 0.7749,
      "label": "Thyroid cartilage",
      "lx": 0.7995,
      "ly": 0.7781,
      "func": "Largest laryngeal cartilage; forms the 'Adam's apple' and protects the vocal cords."
    },
    {
      "id": "rresp239",
      "x": 0.4958,
      "y": 0.243,
      "label": "Opening of auditory (pharyngotympanic) tube",
      "lx": 0.15146,
      "ly": 0.29698,
      "func": "Opening that equalizes air pressure between the middle ear and the nasopharynx."
    },
    {
      "id": "rresp241",
      "x": 0.6146,
      "y": 0.1843,
      "label": "Nasal conchae",
      "lx": 0.13724,
      "ly": 0.07394,
      "func": "Scroll-like projections that warm, humidify, and filter air by increasing the nasal surface area."
    },
    {
      "id": "rresp243",
      "x": 0.2703,
      "y": 0.1315,
      "label": "Nasal meatus",
      "lx": 0.10143,
      "ly": 0.14266,
      "func": "Air passages beneath each concha that channel airflow through the nasal cavity."
    },
    {
      "id": "rresp253",
      "x": 0.9203,
      "y": 0.2331,
      "label": "Nasal vestibule",
      "lx": 0.9203,
      "ly": 0.2831,
      "func": "Entrance to the nasal cavity, just inside the nostril."
    },
    {
      "id": "rresp254",
      "x": 0.9788,
      "y": 0.3217,
      "label": "External nares (nostril)",
      "lx": 0.9788,
      "ly": 0.3717,
      "func": "The nostrils — the openings where air enters the nasal cavity."
    },
    {
      "id": "rresp259",
      "x": 0.4924,
      "y": 0.6733,
      "label": "Glottis",
      "lx": 0.09061,
      "ly": 0.67151,
      "func": "The vocal folds together with the opening between them (rima glottidis) through which air passes to make sound."
    }
  ],
  "ref_resp_larynx": [
    {
      "id": "rresp92",
      "x": 0.3333,
      "y": 0.0976,
      "label": "Epiglottis",
      "lx": 0.3333,
      "ly": 0.1476,
      "func": "Flap of cartilage that folds over the airway during swallowing to keep food out of the larynx."
    },
    {
      "id": "rresp93",
      "x": 0.2667,
      "y": 0.3415,
      "label": "Thyroid cartilage",
      "lx": 0.2667,
      "ly": 0.3915,
      "func": "Largest laryngeal cartilage ('Adam's apple'); protects the vocal cords."
    },
    {
      "id": "rresp94",
      "x": 0.2667,
      "y": 0.6341,
      "label": "Cricothyroid ligament",
      "lx": 0.2667,
      "ly": 0.6841,
      "func": "Connects the thyroid cartilage to the cricoid cartilage below it."
    },
    {
      "id": "rresp260",
      "x": 0.5142,
      "y": 0.6963,
      "label": "Cricoid cartilage",
      "lx": 0.70099,
      "ly": 0.66572,
      "func": "Ring-shaped cartilage at the base of the larynx that connects it to the trachea."
    },
    {
      "id": "rresp261",
      "x": 0.5057,
      "y": 0.8017,
      "label": "Tracheal cartilages",
      "lx": 0.66042,
      "ly": 0.78972,
      "func": "C-shaped rings of cartilage that hold the trachea open."
    }
  ],
  "ref_resp_lungs": [
    {
      "id": "rresp97",
      "x": 0.5,
      "y": 0.0787,
      "label": "Trachea",
      "lx": 0.5,
      "ly": 0.1287,
      "func": "Windpipe; conducts air toward the lungs and divides at the carina."
    },
    {
      "id": "rresp100",
      "x": 0.7222,
      "y": 0.4607,
      "label": "Lobar (secondary) bronchus",
      "lx": 0.7222,
      "ly": 0.5107,
      "func": "Branch of the main bronchus that supplies one lobe of a lung."
    },
    {
      "id": "rresp101",
      "x": 0.7639,
      "y": 0.618,
      "label": "Segmental (tertiary) bronchus",
      "lx": 0.7639,
      "ly": 0.668,
      "func": "Branch of a lobar bronchus that supplies one bronchopulmonary segment."
    },
    {
      "id": "rresp102",
      "x": 0.25,
      "y": 0.4045,
      "label": "Right superior lobe",
      "lx": 0.25,
      "ly": 0.4545,
      "func": "Upper lobe of the right lung — the right lung has three lobes."
    },
    {
      "id": "rresp103",
      "x": 0.25,
      "y": 0.7528,
      "label": "Right middle lobe",
      "lx": 0.25,
      "ly": 0.8028,
      "func": "Middle lobe of the right lung; found only on the right side."
    },
    {
      "id": "rresp104",
      "x": 0.2639,
      "y": 0.8876,
      "label": "Right inferior lobe",
      "lx": 0.2639,
      "ly": 0.9376,
      "func": "Lower lobe of the right lung."
    },
    {
      "id": "rresp105",
      "x": 0.7083,
      "y": 0.1798,
      "label": "Left superior lobe",
      "lx": 0.7083,
      "ly": 0.2298,
      "func": "Upper lobe of the left lung — the left lung has two lobes."
    },
    {
      "id": "rresp106",
      "x": 0.7917,
      "y": 0.8989,
      "label": "Left inferior lobe",
      "lx": 0.7917,
      "ly": 0.9489,
      "func": "Lower lobe of the left lung."
    },
    {
      "id": "rresp262",
      "x": 0.5726,
      "y": 0.3576,
      "label": "Main (primary) bronchus",
      "lx": 0.85562,
      "ly": 0.38333,
      "func": "Conducts air from the trachea into a lung."
    },
    {
      "id": "rresp263",
      "x": 0.5387,
      "y": 0.3448,
      "label": "Carina",
      "lx": 0.53398,
      "ly": 1.0,
      "func": "Ridge where the trachea splits into the two main bronchi; a sensitive cough trigger."
    }
  ],
  "ref_resp_alveoli": [
    {
      "id": "rresp264",
      "x": 0.4472,
      "y": 0.9148,
      "label": "Pulmonary arteriole",
      "lx": 0.2038,
      "ly": 1.0,
      "func": "Small vessel that delivers deoxygenated blood to the alveolar capillaries."
    },
    {
      "id": "rresp269",
      "x": 0.5038,
      "y": 0.8171,
      "label": "Pulmonary venule",
      "lx": 0.21795,
      "ly": 0.68834,
      "func": "Small vessel that carries freshly oxygenated blood away from the alveoli."
    },
    {
      "id": "rresp271",
      "x": 0.3575,
      "y": 0.5671,
      "label": "Alveolar duct / sac",
      "lx": 0.14429,
      "ly": 0.47686,
      "func": "Passage that channels air from the bronchiole into clusters of alveoli."
    },
    {
      "id": "rresp275",
      "x": 0.6538,
      "y": 0.7957,
      "label": "Alveolus",
      "lx": 0.8538,
      "ly": 0.70241,
      "func": "Tiny air sac where gas exchange occurs between the air and the blood."
    },
    {
      "id": "rresp277",
      "x": 0.4594,
      "y": 0.7591,
      "label": "Respiratory bronchiole",
      "lx": 0.10091,
      "ly": 0.83654,
      "func": "Smallest airway; leads air to the alveolar ducts and has a few alveoli of its own."
    }
  ],
  "ref_resp_trachea_histo": [
    {
      "id": "rresp113",
      "x": 0.4744,
      "y": 0.3973,
      "label": "Cilia",
      "lx": 0.4744,
      "ly": 0.4473,
      "func": "Hair-like projections that sweep mucus and trapped particles up toward the throat."
    },
    {
      "id": "rresp278",
      "x": 0.6764,
      "y": 0.7464,
      "label": "Tracheal (seromucous) glands",
      "lx": 0.6764,
      "ly": 0.7964,
      "func": "Glands in the submucosa that secrete watery mucus onto the tracheal lining."
    },
    {
      "id": "rresp280",
      "x": 0.2189,
      "y": 0.2573,
      "label": "Goblet cell",
      "lx": 0.21607,
      "ly": 0.05548,
      "func": "Secretes the mucus that traps inhaled dust and microbes."
    },
    {
      "id": "rresp281",
      "x": 0.9575,
      "y": 0.7226,
      "label": "Mucosa",
      "lx": 0.9575,
      "ly": 0.7726,
      "func": "Inner lining of the trachea — the epithelium plus the underlying lamina propria (loose connective tissue)."
    },
    {
      "id": "rresp283",
      "x": 0.9764,
      "y": 0.4161,
      "label": "Pseudostratified ciliated columnar epithelium",
      "lx": 0.79219,
      "ly": 0.40771,
      "func": "Lining of the trachea that traps inhaled debris in mucus and sweeps it upward."
    }
  ],
  "ref_resp_pleura": [
    {
      "id": "rresp284",
      "x": 0.5972,
      "y": 0.4599,
      "label": "Parietal pleura",
      "lx": 0.31607,
      "ly": 0.45055,
      "func": "Serous membrane lining the chest wall — the outer pleural layer."
    },
    {
      "id": "rresp285",
      "x": 0.5991,
      "y": 0.911,
      "label": "Visceral pleura",
      "lx": 0.29816,
      "ly": 0.88682,
      "func": "Serous membrane covering the surface of the lung — the inner pleural layer."
    },
    {
      "id": "rresp286",
      "x": 0.4151,
      "y": 0.6202,
      "label": "Pleural cavity",
      "lx": 0.28019,
      "ly": 0.69097,
      "func": "Fluid-filled space between the two pleurae that reduces friction during breathing."
    }
  ],
  "ref_resp_muscles": [
    {
      "id": "rresp287",
      "x": 0.2925,
      "y": 0.2889,
      "label": "Intercostal muscles",
      "lx": 0.14533,
      "ly": 0.2673,
      "func": "Muscles between the ribs that raise and lower the rib cage during breathing."
    },
    {
      "id": "rresp288",
      "x": 0.6283,
      "y": 0.5864,
      "label": "Diaphragm",
      "lx": 0.6283,
      "ly": 0.6364,
      "func": "Main muscle of inspiration; contracts and flattens to draw air into the lungs."
    }
  ]
};
