// Built-in pin set shipped with the site.
//
// GENERATED BY tools/key-to-preset.py — regenerate rather than hand-editing:
//   1. Build mode -> place your pins -> "Export pin set" (lands in ~/Downloads)
//   2. python3 tools/key-to-preset.py ~/Downloads/bio40b-practical2-pins-*.json
//   3. commit preset.js
//   4. in the browser, "Reset everything" so your local copy stops shadowing it
//
// Resolution order at load time:
//   localStorage (bio40b_p2_pins)  ->  PRESET_PINS  ->  empty
//
// PRESET_PINS  : { slideId: [ { x, y, label } ] }   x/y are 0..1 of the image
// PRESET_TITLES: { slideId: "renamed title" }       optional overrides

const PRESET_PINS = {};

const PRESET_TITLES = {};

const PRESET_META = {
  generated: null,
  note: "No preset committed yet — the site starts blank so you place your own pins."
};
