#!/usr/bin/env python3
"""Pull the sibling BIOL 40B labeling app's stations in as donor slides.

    python3 tools/import-donor.py

Copies its 19 station images into images/ under a ref_ prefix and converts its
hand-verified PRESET_KEYS into donor.js. Those stations cover the parts of the
exam the lab-bench photos cannot: the histology slides, the conduction system
and the pericardial layers.

Read-only with respect to the labeling repo — nothing there is modified.
"""

import json
import pathlib
import re
import shutil
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
LAB = pathlib.Path.home() / "bio40b-lab-exam-2-labeling"

HEADER = '''// Reference stations donated by the sibling BIOL 40B sites.
//
// Images and hand-verified pin positions come from the labeling app
// (~/bio40b-lab-exam-2-labeling, PRESET_KEYS), copied in rather than linked —
// same arrangement the spelling drill uses. These fill the parts of the exam
// the lab-bench photos cannot show: the histology slides, the conduction
// system, and the pericardial layers.
//
// These slides arrive PRE-PINNED. Your own photos stay blank so you still
// place those yourself. Editing or clearing a donor slide is fine; your
// version then wins over what is shipped here.
//
// GENERATED by tools/import-donor.py — do not hand-edit.

'''


def block(name, text):
    """Pull a top-level `const NAME = {...}` / `[...]` literal out as JSON."""
    m = re.search(r"const\s+%s\s*=\s*[\{\[]" % name, text)
    if not m:
        raise SystemExit(f"error: {name} not found in the labeling app's data.js")
    i = m.end() - 1
    opener = text[i]
    closer = "}" if opener == "{" else "]"
    depth = 0
    for j, ch in enumerate(text[i:], i):
        if ch == opener:
            depth += 1
        elif ch == closer:
            depth -= 1
            if depth == 0:
                break
    return json.loads(text[i:j + 1])


def clamp(v):
    return max(0.0, min(1.0, v))


def main():
    if not LAB.is_dir():
        print(f"error: {LAB} not found")
        return 1

    src = (LAB / "data.js").read_text(encoding="utf-8")
    keys = block("PRESET_KEYS", src)
    info = block("IMAGE_DATA", src)
    order = block("IMAGE_ORDER", src)

    copied = {}
    for sid in order:
        img = LAB / info[sid]["src"]
        if not img.is_file():
            print(f"  skipping {sid}: {img} missing")
            continue
        dst = REPO / "images" / f"ref_{sid}{img.suffix}"
        shutil.copy2(img, dst)
        copied[sid] = f"images/{dst.name}"

    slides, pins = [], {}
    for sid in order:
        if sid not in copied:
            continue
        key = f"ref_{sid}"
        slides.append({
            "id": key,
            "src": copied[sid],
            # their titles are "Station 7 · ..."; the numbering is theirs, not ours
            "title": re.sub(r"^Station \d+ · ", "", info[sid]["title"]),
            "hint": info[sid].get("caption", ""),
            "donor": True,
        })
        out = []
        for p in keys.get(sid, []):
            x, y = clamp(p["x"] / 100.0), clamp(p["y"] / 100.0)
            pin = {"id": f"r{sid[:4]}{p['id']}", "x": round(x, 5), "y": round(y, 5),
                   "label": p["word"]}
            dx, dy = p.get("labelDx"), p.get("labelDy")
            if isinstance(dx, (int, float)) and isinstance(dy, (int, float)) and (dx or dy):
                pin["lx"] = round(clamp(x + dx / 100.0), 5)
                pin["ly"] = round(clamp(y + dy / 100.0), 5)
            if p.get("func"):
                pin["func"] = p["func"]
            out.append(pin)
        if out:
            pins[key] = out

    (REPO / "donor.js").write_text(
        HEADER
        + "const DONOR_SLIDES = " + json.dumps(slides, indent=2, ensure_ascii=False) + ";\n\n"
        + "const DONOR_PINS = " + json.dumps(pins, indent=2, ensure_ascii=False) + ";\n",
        encoding="utf-8")

    total = sum(len(v) for v in pins.values())
    print(f"wrote donor.js — {len(slides)} slides, {total} pins, {len(copied)} images copied")
    return 0


if __name__ == "__main__":
    sys.exit(main())
