#!/usr/bin/env python3
"""Turn an exported pin set into the preset.js that ships with the site.

Usage:
    python3 tools/key-to-preset.py ~/Downloads/bio40b-practical2-pins-2026-07-28.json

Writes preset.js next to index.html. After committing, hit "Reset everything"
in the browser so your device copy stops shadowing the committed preset.
"""

import json
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def load_slide_ids():
    """Read the slide ids out of slides.js so the two files cannot drift."""
    text = (REPO / "slides.js").read_text(encoding="utf-8")
    start = text.index("const SLIDE_ORDER = [")
    end = text.index("]", start)
    body = text[start + len("const SLIDE_ORDER = [") : end]
    return [chunk.strip().strip('",') for chunk in body.split(",") if chunk.strip()]


def js(value):
    """JSON is a close enough subset of JS object literal syntax for this."""
    return json.dumps(value, indent=2, ensure_ascii=False)


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        return 1

    src = Path(sys.argv[1]).expanduser()
    if not src.is_file():
        print(f"error: no such file: {src}")
        return 1

    data = json.loads(src.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or "pins" not in data:
        print("error: that file has no 'pins' key — is it a pin set export?")
        return 1

    known = set(load_slide_ids())
    pins, titles = {}, {}
    dropped, total = [], 0

    for slide_id, plist in (data.get("pins") or {}).items():
        if slide_id not in known:
            dropped.append(slide_id)
            continue
        kept = []
        for p in plist or []:
            try:
                x, y = float(p["x"]), float(p["y"])
            except (KeyError, TypeError, ValueError):
                continue
            label = str(p.get("label", "")).strip()
            if not label:
                continue  # an unnamed pin cannot be a question
            entry = {"x": round(x, 5), "y": round(y, 5), "label": label}
            # Carry a hand-placed label position through, if there is one.
            try:
                entry["lx"] = round(float(p["lx"]), 5)
                entry["ly"] = round(float(p["ly"]), 5)
            except (KeyError, TypeError, ValueError):
                pass
            kept.append(entry)
        if kept:
            pins[slide_id] = kept
            total += len(kept)

    for slide_id, title in (data.get("titles") or {}).items():
        if slide_id in known and str(title).strip():
            titles[slide_id] = str(title).strip()

    out = f"""// Built-in pin set shipped with the site.
//
// GENERATED BY tools/key-to-preset.py — regenerate rather than hand-editing:
//   1. Build mode -> place your pins -> "Export pin set" (lands in ~/Downloads)
//   2. python3 tools/key-to-preset.py ~/Downloads/bio40b-practical2-pins-*.json
//   3. commit preset.js
//   4. in the browser, "Reset everything" so your local copy stops shadowing it
//
// Resolution order at load time:
//   localStorage (bio40b_p2_pins)  ->  PRESET_PINS  ->  empty
//
// PRESET_PINS  : {{ slideId: [ {{ x, y, label }} ] }}   x/y are 0..1 of the image
// PRESET_TITLES: {{ slideId: "renamed title" }}       optional overrides

const PRESET_PINS = {js(pins)};

const PRESET_TITLES = {js(titles)};

const PRESET_META = {{
  generated: "{date.today().isoformat()}",
  pins: {total},
  slides: {len(pins)}
}};
"""

    (REPO / "preset.js").write_text(out, encoding="utf-8")
    print(f"wrote preset.js — {total} pins across {len(pins)} slides")
    if dropped:
        print("skipped unknown slide ids: " + ", ".join(sorted(dropped)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
